import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-charcoal-sf min-h-dvh min-w-dvw">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
